### ISSUE TITLE
Generate Pom

### ISSUE THREAD

**Issue by CubBossa** [sonatype-nexus-community/nexus-repo-github-action#10]
Hello,
I could find no information and tried everything that came to my mind yesterday.
I am uploading a jar to my repo with the following action
```Yaml
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://nexus.leonardbausenwein.de/
          username: admin
          password: ${{ secrets.NEXUS_PASSWORD }}
          format: maven2
          repository: maven-releases
          coordinates: groupId=${{ env.RELEASE_GROUP }} artifactId=${{ env.RELEASE_ARTIFACT }} version=${{ env.RELEASE_VERSION }}
          assets: extension=jar
          filename: ./target/${{ env.RELEASE_ARTIFACT }}-${{ env.RELEASE_VERSION }}.jar
```

now what I need to do is set the attributes `generate-pom=true` and `packaging=jar` for the upload but wherever I put them they are being ignored or cause issues. Is there any way to generate the pom with this github action?
